### ISSUE TITLE
Segmentation fault in GL_Font::readyFont

### ISSUE THREAD

**Issue by alexander982** [LibreCAD/LibreCAD_3#383]
Segmentation fault on [glGenerateMipmap](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glGenerateMipmap.xhtml) call  inside GL_Font::readyFont. May be it's some problem with my old OpenGL system.
```
> glxinfo | grep "OpenGL version"
OpenGL version string: 3.0 Mesa 18.0.5
```

Here gdb backtrace:
```
Thread 1 "librecad" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()

(gdb) backtrace
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff5b0da53 in lc::viewer::opengl::GL_Font::readyFont (
    this=0x1e3a2b0, 
    path="/home/alexander/soft/src/LibreCAD_3/lcviewernoqt/painters/opengl/resources/fonts/ABeeZee-Regular.otf", fontFamily="", fontStyle="")
    at /home/alexander/soft/src/LibreCAD_3/lcviewernoqt/painters/opengl/gl_font.cpp:71
#2  0x00007ffff5b10fe6 in lc::viewer::opengl::Font_Book::createDefaultFont (
    this=0x1b0a350, name="ABeeZee-Regular", 
    file_path="/home/alexander/soft/src/LibreCAD_3/lcviewernoqt/painters/opengl/resources/fonts/ABeeZee-Regular.otf")
    at /home/alexander/soft/src/LibreCAD_3/lcviewernoqt/painters/opengl/font_book.cpp:19
#3  0x00007ffff5b1abec in lc::viewer::opengl::Renderer::createResources (
    this=0x1b0a0c0)
    at /home/alexander/soft/src/LibreCAD_3/lcviewernoqt/painters/opengl/renderer.cpp:44
#4  0x00007ffff5b028c9 in OpenglRenderPainter::create_resources (
    this=0x1dff600)
    at /home/alexander/soft/src/LibreCAD_3/lcviewernoqt/painters/opengl/openglrenderpainter.cpp:26
#5  0x0000000000b957fa in lc::ui::LCADViewer::initializeGL (this=0x1705a00)
    at /home/alexander/soft/src/LibreCAD_3/lcUI/lcadviewer.cpp:139
```

**Comment by alexander982** [comment]
After updating system:
```
glxinfo | grep "OpenGL version"
OpenGL version string: 3.0 Mesa 20.0.8
```
the problem not reproduced.
