### ISSUE TITLE
Segmentation fault in lcunittest

### ISSUE THREAD

**Issue by alexander982** [LibreCAD/LibreCAD_3#393]
```
[       OK ] LinePatternTest.Edition (587 ms)
[ RUN      ] LinePatternTest.Selection
[New Thread 0x7fffc8b96700 (LWP 14212)]

Thread 1 "lcunittest" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()

(gdb) backtrace 
#0  0x0000000000000000 in  ()
#1  0x00007ffff3efd854 in QComboBox::clear() ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#2  0x00007ffff755db9b in lc::ui::widgets::LinePatternSelect::createEntries() (this=0x555555f6d090)
    at /home/alexander/soft/src/LibreCAD_3/lcUI/widgets/linepatternselect.cpp:132
#3  0x00007ffff755e0e4 in lc::ui::widgets::LinePatternSelect::on_addLinePatternEvent(lc::event::AddLinePatternEvent const&) (this=0x555555f6d090, event=...)
    at /home/alexander/soft/src/LibreCAD_3/lcUI/widgets/linepatternselect.cpp:162
#4  0x00007ffff755f70c in Nano::Function<void (lc::event::AddLinePatternEvent const&)> Nano::Function<void (lc::event::AddLinePatternEvent const&)>::bind<lc::ui::widgets::LinePatternSelect, &lc::ui::widgets::LinePatternSelect::on_addLinePatternEvent>(lc::ui::widgets::LinePatternSelect*)::{lambda(void*, lc::event::AddLinePatternEvent const&)#1}::operator()(void*, lc::event::AddLinePatternEvent const&) const (__closure=0x0, this_ptr=0x555555f6d090, args#0=...)
    at /home/alexander/soft/src/LibreCAD_3/lckernel/nano-signal-slot/nano_function.hpp:42
#5  0x00007ffff755f734 in Nano::Function<void (lc::event::AddLinePatternEvent const&)> Nano::Function<void (lc::event::AddLinePatternEvent const&)>::bind<lc::ui::widgets::LinePatternSelect, &lc::ui::widgets::LinePatternSelect::on_addLinePatternEvent>(lc::ui::widgets::LinePatternSelect*)::{lambda(void*, lc::event::AddLinePatternEvent const&)#1}::_FUN(void*, lc::event::AddLinePatternEvent const&) () at /home/alexander/soft/src/LibreCAD_3/lckernel/nano-signal-slot/nano_function.hpp:41
#6  0x00007ffff4d20731 in Nano::Function<void (lc::event::AddLinePatternEvent const&)>::operator()<lc::event::AddLinePatternEvent&>(lc::event::AddLinePatternEvent&) (this=0x7fffffffd420)
    at /home/alexander/soft/src/LibreCAD_3/lckernel/nano-signal-slot/nano_function.hpp:67
```

**Comment by alexander982** [comment]
My new laptop no longer has it
